# Generated by Django 3.2.18 on 2023-05-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_message_recaptcha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'Nuevo Producto', 'verbose_name_plural': 'Lista de Precios'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Proyectos VBA', 'verbose_name_plural': 'Proyectos VBA'},
        ),
    ]
