# Generated by Django 3.2.18 on 2023-05-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20230502_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AddField(
            model_name='education',
            name='link',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
