# Generated by Django 3.2.18 on 2023-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_auto_20230502_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
